name: Test Firmware in Renode

on:
  workflow_run:
    workflows: [ "Build Firmware" ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v3

    - name: Download firmware artifact
      uses: actions/download-artifact@v4
      with:
        name: firmware-elf
        path: build

    - name: Run Renode simulation
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/project" \
          -w /project \
          antmicro/renode \
          bash -c "renode /project/test.resc -e quit-after-run"

    - name: Check UART output
      run: grep "✅ Temperature Normal" output.log
